#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# find the installers and run them iteratively
for f in $(find . -name install.sh)
do
  read -p "Execute ${f}? " -n 1 -r
  echo    # (optional) move to a new line
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
      sh -c "${f}"
  fi
done

# find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
